### ISSUE TITLE
An error in Argo JSON.swift 

### ISSUE THREAD

**Issue by daizhirui** [RLovelett/vscode-swift#37] opened 2018-05-25 07:33 UTC
<img width="637" alt="screen shot 2018-05-25 at 9 31 14 am" src="https://user-images.githubusercontent.com/26495795/40532046-760b84fc-5ffe-11e8-95bf-f35df0742349.png">
I add a case of Bool instead of checking if it is Bool in the case of NSNumber, which results in an error. And vscode reports "Crash 5 times" if I don't fix it.

**Comment by RLovelett** [comment] 2018-05-27 17:16
Is this error in the language server or in the extension?

That directory structure looks like it's in the [language-server](https://github.com/RLovelett/langserver-swift).

**Comment by daizhirui** [comment] 2018-05-27 17:22
Yes, it is in the language-server.

**Comment by RLovelett** [comment] 2018-05-27 17:24
Okay so it looks like your editing the language-server source code in Xcode. I'm not sure what the bug is here exactly.

A little bit more information is going to be needed before I can help you here.

Specifically:

1. What are the exact steps I should perform locally to reproduce this?
2. What are you trying to achieve?
3. How is the experienced behavior different than those expectations?

**Comment by daizhirui** [comment] 2018-05-29 08:28
Okay, here are some steps to reproduce the problem.

First, edit the code about the Bool case as the snapshot I show you.
Then, build a release version of LanguageServer and put it in /usr/local/bin.
Next, set the path of LanguageServer to /usr/local/bin in vscode.
Now, once we open a swift file, a LanguageServer will be launched. After this, execute reload command in vscode’s command panel. You can find that there are two LanguageServers showed in ActivityMonitor. Both of them make a high CPU usage and the mac should start to get very hot.

Maybe what makes my mac hot is not LanguageServer, but the failure of closing old LanguageServer during reload process is a problem.

Now you close the issue and add a reference to the main loop problem. I think it is possible that the main loop problem is a reason.

I hop that you can fix it soon. Or maybe you have fixed it👍!

Best wishes

Zhirui Dai
Informatik, Humboldt Universität zu Berlin

On 27. May 2018, 19:24 +0200, Ryan Lovelett <notifications@github.com>, wrote:

Okay so it looks like your editing the language-server source code in Xcode. I'm not sure what the bug is here exactly.

A little bit more information is going to be needed before I can help you here.

Specifically:

  1.  What are the exact steps I should perform locally to reproduce this?
  2.  What are you trying to achieve?
  3.  How is the experienced behavior different than those expectations?

**Comment by RLovelett** [comment] 2018-05-30 13:37
> First, edit the code about the Bool case as the snapshot I show you.

I'm not sure what impact that would have on anything. Though I'd say that I've recently updated Argo, in https://github.com/RLovelett/langserver-swift/commit/57b83645cff088eeaf37a49ce925895174e643b4, and added a similar `case` to the `switch`. So I think this is already included.

> After this, execute reload command in vscode’s command panel.

Ah yes. This would trigger the same issue identified in #36. Which as you've pointed out should be fixed in https://github.com/RLovelett/langserver-swift/commit/5e40208c3c99f7370c5bbbb776adeba3bcd15272.

For now I'm going to assume that this is a duplicate of #36 and close as they've been fixed. Thank you for the feedback.

**Closed as completed by RLovelett** 2018-05-30 13:37 UTC
Labels: duplicate
