### ISSUE TITLE
XML doc parsing errors

### ISSUE THREAD

**Issue by boozook** [RLovelett/vscode-swift#28] opened 2017-02-22 10:55 UTC
![screen shot 2017-02-22 at 13 51 50](https://cloud.githubusercontent.com/assets/888526/23208542/78db1fa4-f906-11e6-920d-ab790e8dedb5.png)

```bash
swift -version
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9

xcodebuild -version
Xcode 8.2.1
Build version 8C1002
```

**Comment by RLovelett** [comment] 2017-02-22 13:44
I'm going to mark this as a duplicate of [langserver-swift #10](https://github.com/RLovelett/langserver-swift/issues/10).

Thanks @fzzr-! 🙏

**Closed as completed by RLovelett** 2017-02-22 13:44 UTC
